# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'exampleArriveApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for exampleArriveApp

pod 'Curbside'

  target 'exampleArriveApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'exampleArriveAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'exampleArriveApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 end
